trigger:
 - none

jobs:
- job: Amd64
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
      repository: '$(imageName)'
      command: 'build'
      Dockerfile: 'metabase/Dockerfile'
      arguments: '--build-arg BUILD_FROM=homeassistant/amd64-base-debian'
      
- job: Arm
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
      repository: '$(imageName)'
      command: 'build'
      Dockerfile: 'metabase/Dockerfile'
      arguments: '--build-arg BUILD_FROM=homeassistant/aarch64-base-debian'