# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: amd64
  displayName: amd64 (Intel/AMD)
  dependsOn: []
  jobs:
  - job: Build
    displayName: Build
    parameters:
      BUILD_FROM: amd64
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/metabase/Dockerfile'
        tags: |
          $(BUILD_FROM)
